import { defineArrayMember, defineField, defineType } from "sanity";

export const project = defineType({
  name: "project",
  title: "Project",
  type: "document",
  groups: [
    { name: "overview", title: "Overview", default: true },
    { name: "caseStudy", title: "Case study" },
  ],
  fields: [
    defineField({
      name: "title",
      title: "Title",
      type: "string",
      group: "overview",
      validation: (rule) => rule.required().min(2).max(120),
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      group: "overview",
      options: {
        source: "title",
        maxLength: 96,
      },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "shortDescription",
      title: "Short description",
      type: "text",
      group: "overview",
      rows: 3,
      validation: (rule) => rule.required().min(10).max(200),
    }),
    defineField({
      name: "description",
      title: "Description",
      type: "array",
      group: "overview",
      of: [{ type: "block" }],
      validation: (rule) => rule.required().min(1),
    }),
    defineField({
      name: "thumbnail",
      title: "Thumbnail",
      type: "image",
      group: "overview",
      options: { hotspot: true },
      fields: [
        defineField({
          name: "alt",
          title: "Alternative text",
          type: "string",
          validation: (rule) => rule.required(),
        }),
      ],
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "cardImage",
      title: "Card image",
      type: "image",
      group: "overview",
      description:
        "Optional mockup shown on homepage and portfolio cards (laptop/phone on a solid background). If empty, the thumbnail is used.",
      options: { hotspot: true },
      fields: [
        defineField({
          name: "alt",
          title: "Alternative text",
          type: "string",
          validation: (rule) => rule.required(),
        }),
      ],
    }),
    defineField({
      name: "technologies",
      title: "Technologies",
      type: "array",
      group: "overview",
      of: [{ type: "string" }],
      options: { layout: "tags" },
      validation: (rule) => rule.required().min(1),
    }),
    defineField({
      name: "featured",
      title: "Featured",
      type: "boolean",
      group: "overview",
      description: "Show this project in featured sections.",
      initialValue: false,
    }),
    defineField({
      name: "industry",
      title: "Industry",
      type: "string",
      group: "caseStudy",
      description: "e.g. Education, Manufacturing, Healthcare.",
      validation: (rule) => rule.max(80),
    }),
    defineField({
      name: "businessType",
      title: "Business type",
      type: "string",
      group: "caseStudy",
      description: "e.g. Corporate website, AI-powered web application.",
      validation: (rule) => rule.max(120),
    }),
    defineField({
      name: "servicesProvided",
      title: "Services provided",
      type: "array",
      group: "caseStudy",
      of: [defineArrayMember({ type: "string" })],
      options: { layout: "tags" },
    }),
    defineField({
      name: "projectGoals",
      title: "Project goals",
      type: "array",
      group: "caseStudy",
      of: [defineArrayMember({ type: "caseStudyItem" })],
    }),
    defineField({
      name: "challenges",
      title: "Challenges",
      type: "array",
      group: "caseStudy",
      of: [defineArrayMember({ type: "caseStudyChallenge" })],
    }),
    defineField({
      name: "approach",
      title: "Our approach",
      type: "array",
      group: "caseStudy",
      of: [defineArrayMember({ type: "caseStudyItem" })],
    }),
    defineField({
      name: "keyFeatures",
      title: "Key features",
      type: "array",
      group: "caseStudy",
      of: [defineArrayMember({ type: "caseStudyItem" })],
    }),
    defineField({
      name: "results",
      title: "Results",
      type: "array",
      group: "caseStudy",
      of: [defineArrayMember({ type: "caseStudyItem" })],
    }),
    defineField({
      name: "gallery",
      title: "Project gallery",
      type: "array",
      group: "caseStudy",
      of: [
        defineArrayMember({
          type: "image",
          options: { hotspot: true },
          fields: [
            defineField({
              name: "alt",
              title: "Alternative text",
              type: "string",
              validation: (rule) => rule.required(),
            }),
          ],
        }),
      ],
    }),
    defineField({
      name: "testimonial",
      title: "Client testimonial",
      type: "projectClientTestimonial",
      group: "caseStudy",
    }),
    defineField({
      name: "liveUrl",
      title: "Live URL",
      type: "url",
      group: "caseStudy",
      validation: (rule) =>
        rule.uri({
          scheme: ["http", "https"],
        }),
    }),
    defineField({
      name: "projectDuration",
      title: "Project duration",
      type: "string",
      group: "caseStudy",
      description: "e.g. 8 weeks, 3 months.",
      validation: (rule) => rule.max(80),
    }),
    defineField({
      name: "team",
      title: "Team",
      type: "string",
      group: "caseStudy",
      description: "e.g. 4 people, Design + Engineering.",
      validation: (rule) => rule.max(120),
    }),
  ],
  preview: {
    select: {
      title: "title",
      media: "thumbnail",
      subtitle: "shortDescription",
    },
  },
});
